php:
  build: .
  ports:
   - "8080:80"
   - "443:443"
  volumes:
   - ./www/html/alianza:/var/www/html/alianza
   - ./www/html:/var/www/html
   - ./www/alianza:/var/www/alianza
   - ./www:/var/www
  links:
   - db
db:
  image: mysql:5.7
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=dionizio1997
